[package]
name = "ffforf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jetscii = "0.5.3"
pulp = "0.2.2"
lazy_static = "1.4.0"
